import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
import openApiSidebar from './docs/mijn-services/interactie-api/referentie/sidebar';

type GeneratedSidebarItem = {
  type: 'category' | 'doc';
  label?: string;
  id?: string;
  className?: string;
  items?: GeneratedSidebarItem[];
  link?: {type: 'generated-index' | 'doc'; title?: string; slug?: string; id?: string};
  [key: string]: unknown;
};

const generatedApiGroups = openApiSidebar as GeneratedSidebarItem[];
const generatedGroup = (label: string) =>
  generatedApiGroups.find(item => item.type === 'category' && item.label === label);
const coreOperations = generatedGroup('Operaties')?.items ?? [];
const coreSchemas = generatedGroup("Schema's")?.items ?? [];
const taskModule = generatedGroup('Taken');
const taskItems = taskModule?.items ?? [];
const taskOperations = taskItems.filter(item => item.type === 'doc' && item.className?.includes('api-method'));
const taskSchemas = taskItems.filter(item => item.type === 'doc' && item.className === 'schema');

const moduleSidebar = [
  {
    type: 'category' as const,
    label: 'Kernmodule',
    items: [
      {type: 'category' as const, label: 'Operaties', items: coreOperations},
      {type: 'category' as const, label: "Schema's", items: coreSchemas},
    ],
  },
  {
    type: 'category' as const,
    label: 'Uitbreidingsmodules',
    items: [
      {
        type: 'category' as const,
        label: 'Taken',
        link: taskModule?.link,
        items: [
          {type: 'category' as const, label: 'Operaties', items: taskOperations},
          {type: 'category' as const, label: "Schema's", items: taskSchemas},
        ],
      },
    ],
  },
];

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [{
    type: 'category',
    label: 'MijnServices',
    link: {type: 'doc', id: 'mijn-services/index'},
    items: [
      {type: 'autogenerated', dirName: 'mijn-services/klantreis-en-principes'},
      {type: 'autogenerated', dirName: 'mijn-services/scenarios'},
      {type: 'autogenerated', dirName: 'mijn-services/bouwstenen'},
      {type: 'autogenerated', dirName: 'mijn-services/schermprofielen'},
      {
        type: 'category',
        label: 'Interactie API',
        link: {type: 'doc', id: 'mijn-services/interactie-api/index'},
        items: [
          {type: 'doc', id: 'mijn-services/interactie-api/positionering'},
          {type: 'doc', id: 'mijn-services/interactie-api/over-de-portalen-heen'},
          {type: 'doc', id: 'mijn-services/interactie-api/procesoverzicht'},
          ...moduleSidebar,
          ...(process.env.NODE_ENV !== 'production'
            ? [{type: 'doc' as const, id: 'mijn-services/interactie-api/uitgangspunten'}]
            : []),
          {type: 'doc', id: 'mijn-services/interactie-api/vragen'},
        ],
      },
      {type: 'autogenerated', dirName: 'mijn-services/aansluitprofielen'},
      {type: 'autogenerated', dirName: 'mijn-services/architectuur-en-standaarden'},
      {type: 'autogenerated', dirName: 'mijn-services/specificaties'},
    ],
  }],
};

export default sidebars;
